import structlog

from app.agents.base import BaseAgent

logger = structlog.get_logger()


class HealthAgent(BaseAgent):
    def __init__(self):
        super().__init__("health_agent")

    def run(self) -> None:
        from app.config import settings

        health: dict = {}

        # Check database
        health["database"] = self._check_database()

        # Check Redis
        health["redis"] = self._check_redis()

        # Check scraper status
        health["scrapers"] = self._check_scrapers()

        all_healthy = all(v.get("healthy", False) for v in health.values())
        self.log(f"Health check: {'OK' if all_healthy else 'DEGRADED'} - {health}")

        if not all_healthy and settings.GITHUB_TOKEN:
            self._open_github_issue(health)

    def _check_database(self) -> dict:
        try:
            from app.database import SessionLocal

            db = SessionLocal()
            db.execute(__import__("sqlalchemy").text("SELECT 1"))
            db.close()
            return {"healthy": True, "message": "Connected"}
        except Exception as e:
            return {"healthy": False, "message": str(e)}

    def _check_redis(self) -> dict:
        try:
            import redis as redis_lib

            from app.config import settings

            r = redis_lib.from_url(settings.REDIS_URL)
            r.ping()
            return {"healthy": True, "message": "Connected"}
        except Exception as e:
            return {"healthy": False, "message": str(e)}

    def _check_scrapers(self) -> dict:
        try:
            from app.database import SessionLocal
            from app.models.contractor import ScrapeJob

            db = SessionLocal()
            stuck = db.query(ScrapeJob).filter(ScrapeJob.status == "running").count()
            db.close()
            return {"healthy": True, "running_jobs": stuck}
        except Exception as e:
            return {"healthy": False, "message": str(e)}

    def _open_github_issue(self, health: dict) -> None:
        import httpx

        from app.config import settings

        issues = [k for k, v in health.items() if not v.get("healthy")]
        title = f"[ALERT] System health degraded: {', '.join(issues)}"
        body = f"## Health Check Failed\n\n```json\n{health}\n```\n\nAuto-generated by HealthAgent."

        try:
            repo = getattr(settings, "GITHUB_REPO", "your-org/LEAD_GEN_INTELLIGENCE")
            httpx.post(
                f"https://api.github.com/repos/{repo}/issues",
                json={"title": title, "body": body, "labels": ["alert", "health"]},
                headers={"Authorization": f"token {settings.GITHUB_TOKEN}"},
                timeout=10,
            )
            self.log(f"GitHub issue created: {title}")
        except Exception as e:
            self.log(f"Failed to create GitHub issue: {e}", "error")
