name: XPS AUTO MERGE

on:
  pull_request:

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - name: Enable Auto Merge
        run: |
          gh pr merge --auto --merge "${{ github.event.pull_request.number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
